# Generated by Django 4.2.4 on 2023-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(to='queans.question')),
            ],
        ),
    ]
