# Generated by Django 4.2.4 on 2023-09-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queans', '0002_quizlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizlist',
            name='questions',
            field=models.ManyToManyField(to='queans.answer'),
        ),
    ]
